# .github/workflows/deploy.yaml
name: Deploy Hugo to TrueNAS

on:
  push:
    branches: [main]  # Change to your default branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build Hugo Site
        run: hugo

      - name: Setup SSH Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Deploy with rsync
        run: |
          rsync -avh --delete \
            --no-perms --no-owner --no-group \
            -e "ssh -o StrictHostKeyChecking=no" \
            public/ travis@192.168.1.116:/mnt/evere5t/t1mber/tech-site/
